# Generated by Django 3.2.7 on 2021-09-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idade',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
