# Generated by Django 3.2.7 on 2021-09-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-update_at',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-update_at',)},
        ),
    ]
